/*******************************************************************************
 * Copyright (c) 2013 See AUTHORS file.
 * 
 * This file is part of SleepFighter.
 * 
 * SleepFighter is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * SleepFighter is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with SleepFighter. If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
package se.chalmers.dat255.sleepfighter.challenge.math;

import java.util.Random;

import org.apache.commons.math3.linear.DecompositionSolver;
import org.apache.commons.math3.linear.LUDecomposition;
import org.apache.commons.math3.linear.RealMatrix;
import org.apache.commons.math3.linear.RealVector;

import se.chalmers.dat255.sleepfighter.utils.debug.Debug;
import se.chalmers.dat255.sleepfighter.utils.math.MatrixUtil;
import android.content.Context;

import com.google.common.math.DoubleMath;

/*
 * Challenge: Solve a system of linear equations with three variables.
 * For the system of linear equations Ax = b, where x = (x1 x2 x3), the user is to solve
 * for either x1 or x2(just solving for x3 is too easy). 
 * The systems of linear equations generated by this class, have an unique solution, 
 * and are thus trivially solved using Gaussian elimination. 
 */
public class LinearEquationProblem implements MathProblem {
	
	private final Context context;
	
	// we use a 3x3 coefficent matrix.
	private static final int MATRIX_SIZE = 3;
	
	private int solution;
	
	private String renderedString;
	
	private Random rng = new Random();
	
	// The coefficient-matrix. 
	private RealMatrix A;
	
	// The constant vector b.
	private RealVector b;
	
	private int variableToSolveFor;
	
	public String render() {
		return this.renderedString;
	}
	
	public int solution() {
		return this.solution;
	}
	
	// Create A
	RealMatrix createCoefficients() {
		return MatrixUtil.createRandomMatrix(rng, MATRIX_SIZE, -8, 16, true);
	}
	
	// create b
	RealVector createConstantVector() {
		// 20, 60
		return MatrixUtil.createRandomVector(rng, MATRIX_SIZE, 25, 60, true);
	}
	
	public void newProblem() {
		
		generateProblem();
		Debug.d("coeff: " + this.A);
		Debug.d("constants: " + this.b);
		Debug.d("variable: " + this.variableToSolveFor);
		Debug.d("solution: " + this.solution);

		// now render the problem
		doRender();
		Debug.d("rendered problem: " + this.renderedString);

	}
	
	// find a system of linear equations with a real solution(because real solutions are easy to input on the android keyboard)
	private void generateProblem() {
		
		// We want to generate a system of linear equations Ax = b(where x = (x1 x2 x3)).
		// We'll cache the LU-decomposition of the coefficient-matrix A, and then keep on 
		// generating a constant vector b until we got a real solution for either x1 or y2.
		this.A = createCoefficients();
		DecompositionSolver ALU = new LUDecomposition(this.A).getSolver();
		
		int attempts = 0;
		
		boolean foundb = false;
		do { 
			
			Debug.d("try again");
			
			// if after 40 attempts we still can't find a good constants vector, we should give up on this 
			// coefficient matrix and try creating a new one.
			if(attempts == 40) {
				this.A = createCoefficients();
				ALU = new LUDecomposition(this.A).getSolver();
				attempts = 0;
			}
		
			this.b = this.createConstantVector();
			RealVector vsolution = MatrixUtil.solveLinearEquationSystem(ALU, b);
			
			// x1, x2, and x3 must all be integers. 
			if(!(isInteger(vsolution.getEntry(0)) &&
					isInteger(vsolution.getEntry(1)) &&
					isInteger(vsolution.getEntry(2))) ) {
				attempts++;
				continue;
			}
			
			// TODO: ensure the solutions aren't too big.
			
			this.variableToSolveFor = -1;
			
			if(!isBoringSolution((int)vsolution.getEntry(0))) {
				Debug.d("found solution x");
				this.variableToSolveFor = 0;
				
			} else if(!isBoringSolution((int)vsolution.getEntry(1))) {
				Debug.d("found solution y");
				this.variableToSolveFor = 1;
			}

			if(this.variableToSolveFor != -1) {
				foundb = true;
				Debug.d("soluton: " + vsolution); 
				this.solution = (int)vsolution.getEntry(this.variableToSolveFor);
			}
			
			attempts++;
			
		} while(!foundb);
	}
	
	// boring solutions are solution that are small, boring numbers like 1 and 2. 
	// We will not allow boring solutions!
	private static boolean isBoringSolution(int solution) {
		return solution == 0 || Math.abs(solution) == 1 || Math.abs(solution) == 2;
	}
	
	private static boolean isInteger(double d) {
		return DoubleMath.isMathematicalInteger(d);
	}
	
	private void doRender() {
		
		// begin table. 
		this.renderedString =  "\\[\\table "; // "\\[\\table 2x + 3y + 4z, =, 4; 4x + 2y + 6z , =, 6\\]";
		
		for(int row = 0; row < MATRIX_SIZE; ++row) {
			
			// current row
			double[] r = this.A.getRow(row);
					
			// render the terms
			this.renderedString += 
					renderTerm(r[0], getVariableString(0), true)+
					renderTerm(r[1], getVariableString(1), false) + 
					renderTerm(r[2], getVariableString(2), false); 
			
			// now the constant.
			this.renderedString += " , = , " + (int)this.b.getEntry(row) + ";";
		}
		
		// close the table
		this.renderedString += "\\]";
		
		// now write the desciption.
		this.renderedString += "<br> Solve for $" + getVariableString(this.variableToSolveFor) + "$";
	}
	
	private static String getVariableString(int variable) {
		if(variable == 0) {
			return "x";
		} else if(variable == 1) {
			return "y";
		} else if(variable == 2) {
			return "z";
		} else {
			throw new IllegalArgumentException("This should not happen!");
		}
	}
	
	private static String renderTerm(double value, String variable, boolean isFirstTerm) {
		
		
		// TODO, write 1y as y. 
		
		int v = ((int)value);
		String s;
		if(isFirstTerm) {
			s =  Integer.toString(v)  + variable;
		} else {
			if(v < 0) {
				s = ", - , " + Integer.toString(Math.abs(v))  + variable;
			} else {
				s = " , + , " + Integer.toString(v)  + variable;
			}
		}
		return s + " ";
	}
	
	public LinearEquationProblem(final Context context) {
		this.context = context;
	}
	
}
