package se.chalmers.dat255.sleepfighter.challenge.minesweeper;
import org.bridj.Pointer;
import org.bridj.ann.Constructor;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
import org.bridj.cpp.CPPObject;
/**
 * \brief This class represents dimensions.<br>
 * * Please note that it is immutable.<br>
 * <i>native declaration : line 28</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("se.chalmers.dat255.sleepfighter.challenge.minesweeper") 
public class Dimensions extends CPPObject {
	/** Original signature : <code>Dimensions(value_type, value_type)</code> */
	@Name("Dimensions") 
	@Constructor(0) 
	public dimensions(int w, int h) {
		super((Void)null, 0, w, h);
	}
	/**
	 * Original signature : <code>value_type getWidth()</code><br>
	 * <i>native declaration : line 35</i>
	 */
	native public int getWidth();
	/**
	 * Original signature : <code>value_type getHeight()</code><br>
	 * <i>native declaration : line 39</i>
	 */
	native public int getHeight();
	/**
	 * Original signature : <code>value_type size()</code><br>
	 * <i>native declaration : line 43</i>
	 */
	native public int size();
	public Dimensions() {
		super();
	}
	public Dimensions(Pointer pointer) {
		super(pointer);
	}
}
