package se.chalmers.dat255.sleepfighter.challenge.minesweeper;
import org.bridj.Pointer;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.cpp.CPPObject;
/**
 * <i>native declaration : line 305</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("se.chalmers.dat255.sleepfighter.challenge.minesweeper") 
public class MinesweeperConfig extends CPPObject {
	/**
	 * board config.<br>
	 * C type : Dimensions&
	 */
	@Field(0) 
	public Pointer<Dimensions > dim() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * board config.<br>
	 * C type : Dimensions&
	 */
	@Field(0) 
	public MinesweeperConfig dim(Pointer<Dimensions > dim) {
		this.io.setPointerField(this, 0, dim);
		return this;
	}
	@Field(1) 
	public int mineCount() {
		return this.io.getIntField(this, 1);
	}
	@Field(1) 
	public MinesweeperConfig mineCount(int mineCount) {
		this.io.setIntField(this, 1, mineCount);
		return this;
	}
	/**
	 * initial move position.<br>
	 * C type : Position&
	 */
	@Field(2) 
	public Pointer<Position > pos() {
		return this.io.getPointerField(this, 2);
	}
	/**
	 * initial move position.<br>
	 * C type : Position&
	 */
	@Field(2) 
	public MinesweeperConfig pos(Pointer<Position > pos) {
		this.io.setPointerField(this, 2, pos);
		return this;
	}
	/** solver config. */
	@Field(3) 
	public boolean requireSolvable() {
		return this.io.getBooleanField(this, 3);
	}
	/** solver config. */
	@Field(3) 
	public MinesweeperConfig requireSolvable(boolean requireSolvable) {
		this.io.setBooleanField(this, 3, requireSolvable);
		return this;
	}
	@Field(4) 
	public int maxSolvingTries() {
		return this.io.getIntField(this, 4);
	}
	@Field(4) 
	public MinesweeperConfig maxSolvingTries(int maxSolvingTries) {
		this.io.setIntField(this, 4, maxSolvingTries);
		return this;
	}
	public MinesweeperConfig() {
		super();
	}
	public MinesweeperConfig(Pointer pointer) {
		super(pointer);
	}
}
