package se.chalmers.dat255.sleepfighter.challenge.minesweeper;
import org.bridj.FlagSet;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Name;
import org.bridj.cpp.CPPObject;
import se.chalmers.dat255.sleepfighter.challenge.minesweeper.SeChalmersDat255SleepfighterChallengeMinesweeperLibrary.SquareState;
/**
 * <i>native declaration : line 160</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("se.chalmers.dat255.sleepfighter.challenge.minesweeper") 
public class Square extends CPPObject {
	/**
	 * Original signature : <code>minevalue getValue()</code><br>
	 * <i>native declaration : line 167</i>
	 */
	native public int getValue();
	/**
	 * Original signature : <code>bool isMine()</code><br>
	 * <i>native declaration : line 171</i>
	 */
	native public boolean isMine();
	/**
	 * Original signature : <code>bool isEmpty()</code><br>
	 * <i>native declaration : line 175</i>
	 */
	native public boolean isEmpty();
	/**
	 * Original signature : <code>SquareState getState()</code><br>
	 * <i>native declaration : line 179</i>
	 */
	public IntValuedEnum<SquareState > getState() {
		return FlagSet.fromValue(getState$2(), SquareState.class);
	}
	@Name("getState") 
	protected native int getState$2();
	public Square() {
		super();
	}
	public Square(Pointer pointer) {
		super(pointer);
	}
}
